# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Zach's Website"
tagline:          "A Simple Website"
description:      "Zach's Website"
url:              https://github.com/zachpanz88

author:
  name:           'Zach P'
  url:            https://github.com/zachpanz88

paginate:         3

# Custom vars
version:          1.0.0

github:           https://github.com/zachpanz88
  repo:           https://github.com/zachpanz88/zachpanz88.github.io
