# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Zach's Website"
tagline:          "A Website About Code"
description:      "Zach's Code Website"
url:              http://github.com/zachpanz88

author:
  name:           'Zach P'
  url:            https://github.com/zachpanz88

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/zachpanz88/zachpanz88.github.io
